apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pywebsvr-deployment
spec:
  selector:
    matchLabels:
      app: pywebsvr
  replicas: 1
  template: 
    metadata:
      labels:
        app: pywebsvr
    spec:
      containers:
      - name: pywebsvr
        image: ranada/pywebsvr:0.0.1
        ports:
        - containerPort: 8080
